### ISSUE TITLE
Failed with simple example

### ISSUE THREAD

**Issue by srenatus** [myitcv/neovim#35]
Hi there. Trying to build a small helper with this, I failed miserably. The following [code](https://gist.github.com/srenatus/f9ba5b2e1cb834647c7f) prints a client, but never reaches [line 32](https://gist.github.com/srenatus/f9ba5b2e1cb834647c7f#file-n-go-L32). What could be wrong? Tried it with `NVIM_LISTEN_ADDRESS=127.0.0.1:7777` and the respective changes, too, no success.

``` go
    addr := os.Getenv("NVIM_LISTEN_ADDRESS")
    if addr == "" {
        log.Fatal("NVIM_LISTEN_ADDRESS is not set")
    }

    sock, err := net.ResolveUnixAddr("unix", addr)
    if err != nil {
        log.Fatal(err)
    }

    c, err := neovim.NewUnixClient(neovim.NullInitMethod, "unix", nil, sock, nil)
    if err != nil {
        log.Fatal(err)
    }
    log.Printf("got client: %s\n", c)

    b, err := c.GetCurrentBuffer()
    if err != nil {
        log.Fatal(err)
    }
    log.Printf("got current buffer: %s\n", b)
```

Thanks a lot :smiley:

**Comment by ghost** [comment]
Call [Run](https://godoc.org/github.com/myitcv/neovim#Client.Run) before calling GetCurrentBuffer.

**Comment by srenatus** [comment]
Oh dear. Thank you so much.
